name = "smiski-photos-worker"
main = "index.js"
compatibility_date = "2024-11-27"
compatibility_flags = ["nodejs_compat"]

# Bind KV namespaces
kv_namespaces = [
  { binding = "IMAGE_LINKS", id = "6aa6f882d1364f40baa220d51664ea36" },
  { binding = "SECRETS", id = "69469b1204824e618c865e66be17e5c6" }
]

# Route configuration
routes = [
  "https://smiski-travel.us/*"
]

# Observability (logs)
[observability]
enabled = true
